#!/bin/bash
REPO="https://github.com/vxb-hmz/sxwe23rys/raw/refs/heads/main/"
ns_domain_cloudflare() {
    DOMAIN=$(cat /etc/xray/domain)
    SUB=$(tr </dev/urandom -dc a-z0-9 | head -c7)
    SUB_DOMAIN=${SUB}.${DOMAIN}
    NS_DOMAIN=ns-${SUB_DOMAIN}
CF_TOKEN="ZJ-HMdxrRwq54Mpv7NbuNlqOW11SaXIKQRQBqLLa"
set -euo pipefail
IP=$(wget -qO- ipinfo.io/ip)
echo "Updating DNS NS for ${NS_DOMAIN}..."

# Get Zone ID
ZONE=$(
    curl -sLX GET "https://api.cloudflare.com/client/v4/zones?name=${DOMAIN}&status=active" \
    -H "Authorization: Bearer ${CF_TOKEN}" \
    -H "Content-Type: application/json" | jq -r '.result[0].id'
)

# Check if NS record exists
RECORD=$(
    curl -sLX GET "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records?name=${NS_DOMAIN}" \
    -H "Authorization: Bearer ${CF_TOKEN}" \
    -H "Content-Type: application/json" | jq -r '.result[0].id // empty'
)

# Create record if not exists
if [ -z "$RECORD" ]; then
    RECORD=$(
        curl -sLX POST "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records" \
        -H "Authorization: Bearer ${CF_TOKEN}" \
        -H "Content-Type: application/json" \
        --data '{"type":"NS","name":"'"${NS_DOMAIN}"'","content":"'"${DOMAIN}"'","proxied":false}' | jq -r '.result.id'
    )
fi

# Update the record
curl -sLX PUT "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records/${RECORD}" \
    -H "Authorization: Bearer ${CF_TOKEN}" \
    -H "Content-Type: application/json" \
    --data '{"type":"NS","name":"'"${NS_DOMAIN}"'","content":"'"${DOMAIN}"'","proxied":false}'

echo "$NS_DOMAIN" >/etc/xray/dns
}

setup_dnstt() {
    cd
    rm -rf *
    mkdir -p /etc/slowdns
    wget -O dnstt-server "${REPO}slowdns/dnstt-server" && chmod +x dnstt-server >/dev/null 2>&1
    wget -O dnstt-client "${REPO}slowdns/dnstt-client" && chmod +x dnstt-client >/dev/null 2>&1
    ./dnstt-server -gen-key -privkey-file server.key -pubkey-file server.pub
    chmod +x *
    mv * /etc/slowdns
    wget -O /etc/systemd/system/client.service "${REPO}slowdns/client" >/dev/null 2>&1
    wget -O /etc/systemd/system/server.service "${REPO}slowdns/server" >/dev/null 2>&1
    sed -i "s/xxxx/$NS_DOMAIN/g" /etc/systemd/system/client.service
    sed -i "s/xxxx/$NS_DOMAIN/g" /etc/systemd/system/server.service
}
ns_domain_cloudflare
setup_dnstt
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
iptables-save >/etc/iptables/rules.v4 >/dev/null 2>&1
iptables-save >/etc/iptables.up.rules >/dev/null 2>&1
netfilter-persistent save >/dev/null 2>&1
netfilter-persistent reload >/dev/null 2>&1
systemctl enable iptables >/dev/null 2>&1
systemctl start iptables >/dev/null 2>&1
systemctl restart iptables >/dev/null 2>&1
